services:
  data:
    image: postgres:latest
    container_name: simple-contact-data
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - pg_data:/var/lib/postgresql/data
    # ports:
    #   - "5432:5432"
    networks:
      - simple-contact-network

  api:
      build:
        context: ./simple-contact-api
        dockerfile: Dockerfile
      container_name: simple-contact-api
      depends_on:
        - data
      # ports:
      #   - "8080:8080"
      environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://data:5432/postgres
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      networks:
        - simple-contact-network

  ui:
    build:
      context: ./simple-contact-ui
      dockerfile: Dockerfile
    container_name: simple-contact-ui
    depends_on:
      - api
    ports:
      - "80:80"
    networks:
      - simple-contact-network

volumes:
  pg_data:

networks:
  simple-contact-network:
    driver: bridge
